[2025-03-10T08:37:35.399+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-10T08:37:35.431+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: tiki_orchestration_dag.trigger_transform manual__2025-03-10T08:26:29.057421+00:00 [queued]>
[2025-03-10T08:37:35.446+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: tiki_orchestration_dag.trigger_transform manual__2025-03-10T08:26:29.057421+00:00 [queued]>
[2025-03-10T08:37:35.447+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 2
[2025-03-10T08:37:35.468+0000] {taskinstance.py:2890} INFO - Executing <Task(TriggerDagRunOperator): trigger_transform> on 2025-03-10 08:26:29.057421+00:00
[2025-03-10T08:37:35.483+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=1023) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-03-10T08:37:35.485+0000] {standard_task_runner.py:72} INFO - Started process 1025 to run task
[2025-03-10T08:37:35.486+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'tiki_orchestration_dag', 'trigger_transform', 'manual__2025-03-10T08:26:29.057421+00:00', '--job-id', '340', '--raw', '--subdir', 'DAGS_FOLDER/tiki_etl_orchestration.py', '--cfg-path', '/tmp/tmpnjx7by6v']
[2025-03-10T08:37:35.487+0000] {standard_task_runner.py:105} INFO - Job 340: Subtask trigger_transform
[2025-03-10T08:37:36.038+0000] {task_command.py:467} INFO - Running <TaskInstance: tiki_orchestration_dag.trigger_transform manual__2025-03-10T08:26:29.057421+00:00 [running]> on host c77555d100c4
[2025-03-10T08:37:36.231+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='tiki_orchestration_dag' AIRFLOW_CTX_TASK_ID='trigger_transform' AIRFLOW_CTX_EXECUTION_DATE='2025-03-10T08:26:29.057421+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-03-10T08:26:29.057421+00:00'
[2025-03-10T08:37:36.235+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-03-10T08:37:36.236+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-03-10T08:37:36.237+0000] {logging_mixin.py:190} INFO - Current task name:trigger_transform state:running start_date:2025-03-10 08:37:35.432810+00:00
[2025-03-10T08:37:36.238+0000] {logging_mixin.py:190} INFO - Dag name:tiki_orchestration_dag and current dag run status:running
[2025-03-10T08:37:36.238+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-03-10T08:37:36.388+0000] {trigger_dagrun.py:257} INFO - Waiting for tiki_transform_dag on 2025-03-10 08:37:36.239692+00:00 to become allowed state ['success'] ...
[2025-03-10T08:38:36.402+0000] {trigger_dagrun.py:257} INFO - Waiting for tiki_transform_dag on 2025-03-10 08:37:36.239692+00:00 to become allowed state ['success'] ...
[2025-03-10T08:39:36.409+0000] {trigger_dagrun.py:257} INFO - Waiting for tiki_transform_dag on 2025-03-10 08:37:36.239692+00:00 to become allowed state ['success'] ...
[2025-03-10T08:40:36.417+0000] {trigger_dagrun.py:257} INFO - Waiting for tiki_transform_dag on 2025-03-10 08:37:36.239692+00:00 to become allowed state ['success'] ...
[2025-03-10T08:41:36.423+0000] {trigger_dagrun.py:257} INFO - Waiting for tiki_transform_dag on 2025-03-10 08:37:36.239692+00:00 to become allowed state ['success'] ...
[2025-03-10T08:42:36.431+0000] {trigger_dagrun.py:257} INFO - Waiting for tiki_transform_dag on 2025-03-10 08:37:36.239692+00:00 to become allowed state ['success'] ...
[2025-03-10T08:43:36.439+0000] {trigger_dagrun.py:257} INFO - Waiting for tiki_transform_dag on 2025-03-10 08:37:36.239692+00:00 to become allowed state ['success'] ...
[2025-03-10T08:44:36.456+0000] {trigger_dagrun.py:257} INFO - Waiting for tiki_transform_dag on 2025-03-10 08:37:36.239692+00:00 to become allowed state ['success'] ...
[2025-03-10T08:45:36.468+0000] {trigger_dagrun.py:257} INFO - Waiting for tiki_transform_dag on 2025-03-10 08:37:36.239692+00:00 to become allowed state ['success'] ...
[2025-03-10T08:46:36.475+0000] {trigger_dagrun.py:257} INFO - Waiting for tiki_transform_dag on 2025-03-10 08:37:36.239692+00:00 to become allowed state ['success'] ...
[2025-03-10T08:47:36.481+0000] {trigger_dagrun.py:257} INFO - Waiting for tiki_transform_dag on 2025-03-10 08:37:36.239692+00:00 to become allowed state ['success'] ...
[2025-03-10T08:48:36.493+0000] {trigger_dagrun.py:257} INFO - Waiting for tiki_transform_dag on 2025-03-10 08:37:36.239692+00:00 to become allowed state ['success'] ...
[2025-03-10T08:49:36.506+0000] {trigger_dagrun.py:257} INFO - Waiting for tiki_transform_dag on 2025-03-10 08:37:36.239692+00:00 to become allowed state ['success'] ...
[2025-03-10T08:50:36.514+0000] {trigger_dagrun.py:257} INFO - Waiting for tiki_transform_dag on 2025-03-10 08:37:36.239692+00:00 to become allowed state ['success'] ...
[2025-03-10T08:51:36.527+0000] {trigger_dagrun.py:257} INFO - Waiting for tiki_transform_dag on 2025-03-10 08:37:36.239692+00:00 to become allowed state ['success'] ...
[2025-03-10T08:52:36.536+0000] {trigger_dagrun.py:257} INFO - Waiting for tiki_transform_dag on 2025-03-10 08:37:36.239692+00:00 to become allowed state ['success'] ...
[2025-03-10T08:53:36.719+0000] {taskinstance.py:3313} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/trigger_dagrun.py", line 269, in execute
    raise AirflowException(f"{self.trigger_dag_id} failed with failed states {state}")
airflow.exceptions.AirflowException: tiki_transform_dag failed with failed states failed
[2025-03-10T08:53:36.845+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2025-03-10T08:53:36.846+0000] {logging_mixin.py:190} INFO - Task start:2025-03-10 08:37:35.432810+00:00 end:2025-03-10 08:53:36.824842+00:00 duration:961.392032
[2025-03-10T08:53:36.849+0000] {logging_mixin.py:190} INFO - Task:<Task(TriggerDagRunOperator): trigger_transform> dag:<DAG: tiki_orchestration_dag> dagrun:<DagRun tiki_orchestration_dag @ 2025-03-10 08:26:29.057421+00:00: manual__2025-03-10T08:26:29.057421+00:00, state:running, queued_at: 2025-03-10 08:26:29.087039+00:00. externally triggered: True>
[2025-03-10T08:53:36.850+0000] {logging_mixin.py:190} INFO - Failure caused by tiki_transform_dag failed with failed states failed
[2025-03-10T08:53:36.852+0000] {taskinstance.py:1226} INFO - Marking task as UP_FOR_RETRY. dag_id=tiki_orchestration_dag, task_id=trigger_transform, run_id=manual__2025-03-10T08:26:29.057421+00:00, execution_date=20250310T082629, start_date=20250310T083735, end_date=20250310T085336
[2025-03-10T08:53:37.012+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-03-10T08:53:37.020+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 340 for task trigger_transform (tiki_transform_dag failed with failed states failed; 1025)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3006, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 274, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3161, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3185, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/trigger_dagrun.py", line 269, in execute
    raise AirflowException(f"{self.trigger_dag_id} failed with failed states {state}")
airflow.exceptions.AirflowException: tiki_transform_dag failed with failed states failed
[2025-03-10T08:53:37.138+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-03-10T08:53:37.349+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-10T08:53:37.352+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
