[2025-03-11T17:28:00.692+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-11T17:28:00.733+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: tiki_etl_orchestration.transform_data manual__2025-03-11T17:16:49.952427+00:00 [queued]>
[2025-03-11T17:28:00.932+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: tiki_etl_orchestration.transform_data manual__2025-03-11T17:16:49.952427+00:00 [queued]>
[2025-03-11T17:28:00.932+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 4
[2025-03-11T17:28:00.951+0000] {taskinstance.py:2890} INFO - Executing <Task(TriggerDagRunOperator): transform_data> on 2025-03-11 17:16:49.952427+00:00
[2025-03-11T17:28:00.967+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=763) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-03-11T17:28:00.969+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'tiki_etl_orchestration', 'transform_data', 'manual__2025-03-11T17:16:49.952427+00:00', '--job-id', '613', '--raw', '--subdir', 'DAGS_FOLDER/tiki_etl_orchestration.py', '--cfg-path', '/tmp/tmp2dgha1wb']
[2025-03-11T17:28:00.970+0000] {standard_task_runner.py:72} INFO - Started process 765 to run task
[2025-03-11T17:28:00.971+0000] {standard_task_runner.py:105} INFO - Job 613: Subtask transform_data
[2025-03-11T17:28:01.046+0000] {task_command.py:467} INFO - Running <TaskInstance: tiki_etl_orchestration.transform_data manual__2025-03-11T17:16:49.952427+00:00 [running]> on host 5c8190d7da62
[2025-03-11T17:28:01.188+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='tiki_etl_orchestration' AIRFLOW_CTX_TASK_ID='transform_data' AIRFLOW_CTX_EXECUTION_DATE='2025-03-11T17:16:49.952427+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-03-11T17:16:49.952427+00:00'
[2025-03-11T17:28:01.193+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-03-11T17:28:01.194+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-03-11T17:28:01.195+0000] {logging_mixin.py:190} INFO - Current task name:transform_data state:running start_date:2025-03-11 17:28:00.734370+00:00
[2025-03-11T17:28:01.195+0000] {logging_mixin.py:190} INFO - Dag name:tiki_etl_orchestration and current dag run status:running
[2025-03-11T17:28:01.196+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-03-11T17:28:01.316+0000] {trigger_dagrun.py:257} INFO - Waiting for tiki_transform_dag on 2025-03-11 17:28:01.197706+00:00 to become allowed state ['success'] ...
[2025-03-11T17:29:01.326+0000] {trigger_dagrun.py:257} INFO - Waiting for tiki_transform_dag on 2025-03-11 17:28:01.197706+00:00 to become allowed state ['success'] ...
[2025-03-11T17:30:01.332+0000] {trigger_dagrun.py:257} INFO - Waiting for tiki_transform_dag on 2025-03-11 17:28:01.197706+00:00 to become allowed state ['success'] ...
[2025-03-11T17:31:01.338+0000] {trigger_dagrun.py:257} INFO - Waiting for tiki_transform_dag on 2025-03-11 17:28:01.197706+00:00 to become allowed state ['success'] ...
[2025-03-11T17:32:01.345+0000] {trigger_dagrun.py:257} INFO - Waiting for tiki_transform_dag on 2025-03-11 17:28:01.197706+00:00 to become allowed state ['success'] ...
[2025-03-11T17:33:01.352+0000] {trigger_dagrun.py:257} INFO - Waiting for tiki_transform_dag on 2025-03-11 17:28:01.197706+00:00 to become allowed state ['success'] ...
[2025-03-11T17:34:01.361+0000] {trigger_dagrun.py:257} INFO - Waiting for tiki_transform_dag on 2025-03-11 17:28:01.197706+00:00 to become allowed state ['success'] ...
[2025-03-11T17:35:01.373+0000] {trigger_dagrun.py:257} INFO - Waiting for tiki_transform_dag on 2025-03-11 17:28:01.197706+00:00 to become allowed state ['success'] ...
[2025-03-11T17:36:01.379+0000] {trigger_dagrun.py:257} INFO - Waiting for tiki_transform_dag on 2025-03-11 17:28:01.197706+00:00 to become allowed state ['success'] ...
[2025-03-11T17:37:01.386+0000] {trigger_dagrun.py:257} INFO - Waiting for tiki_transform_dag on 2025-03-11 17:28:01.197706+00:00 to become allowed state ['success'] ...
[2025-03-11T17:38:01.391+0000] {trigger_dagrun.py:257} INFO - Waiting for tiki_transform_dag on 2025-03-11 17:28:01.197706+00:00 to become allowed state ['success'] ...
[2025-03-11T17:39:01.396+0000] {trigger_dagrun.py:257} INFO - Waiting for tiki_transform_dag on 2025-03-11 17:28:01.197706+00:00 to become allowed state ['success'] ...
[2025-03-11T17:40:01.402+0000] {trigger_dagrun.py:257} INFO - Waiting for tiki_transform_dag on 2025-03-11 17:28:01.197706+00:00 to become allowed state ['success'] ...
[2025-03-11T17:41:01.409+0000] {trigger_dagrun.py:257} INFO - Waiting for tiki_transform_dag on 2025-03-11 17:28:01.197706+00:00 to become allowed state ['success'] ...
[2025-03-11T17:42:01.406+0000] {trigger_dagrun.py:257} INFO - Waiting for tiki_transform_dag on 2025-03-11 17:28:01.197706+00:00 to become allowed state ['success'] ...
[2025-03-11T17:43:01.426+0000] {trigger_dagrun.py:257} INFO - Waiting for tiki_transform_dag on 2025-03-11 17:28:01.197706+00:00 to become allowed state ['success'] ...
[2025-03-11T17:44:01.459+0000] {taskinstance.py:3313} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/trigger_dagrun.py", line 269, in execute
    raise AirflowException(f"{self.trigger_dag_id} failed with failed states {state}")
airflow.exceptions.AirflowException: tiki_transform_dag failed with failed states failed
[2025-03-11T17:44:01.486+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2025-03-11T17:44:01.487+0000] {logging_mixin.py:190} INFO - Task start:2025-03-11 17:28:00.734370+00:00 end:2025-03-11 17:44:01.482584+00:00 duration:960.748214
[2025-03-11T17:44:01.488+0000] {logging_mixin.py:190} INFO - Task:<Task(TriggerDagRunOperator): transform_data> dag:<DAG: tiki_etl_orchestration> dagrun:<DagRun tiki_etl_orchestration @ 2025-03-11 17:16:49.952427+00:00: manual__2025-03-11T17:16:49.952427+00:00, state:running, queued_at: 2025-03-11 17:16:51.079914+00:00. externally triggered: True>
[2025-03-11T17:44:01.489+0000] {logging_mixin.py:190} INFO - Failure caused by tiki_transform_dag failed with failed states failed
[2025-03-11T17:44:01.490+0000] {taskinstance.py:1226} INFO - Marking task as UP_FOR_RETRY. dag_id=tiki_etl_orchestration, task_id=transform_data, run_id=manual__2025-03-11T17:16:49.952427+00:00, execution_date=20250311T171649, start_date=20250311T172800, end_date=20250311T174401
[2025-03-11T17:44:01.547+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-03-11T17:44:01.549+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 613 for task transform_data (tiki_transform_dag failed with failed states failed; 765)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3006, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 274, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3161, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3185, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/trigger_dagrun.py", line 269, in execute
    raise AirflowException(f"{self.trigger_dag_id} failed with failed states {state}")
airflow.exceptions.AirflowException: tiki_transform_dag failed with failed states failed
[2025-03-11T17:44:01.609+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-03-11T17:44:01.685+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-11T17:44:01.688+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
