[2025-03-12T14:48:45.972+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-12T14:48:45.989+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: tiki_transform_dag.transform_data manual__2025-03-12T14:37:42.059637+00:00 [queued]>
[2025-03-12T14:48:45.998+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: tiki_transform_dag.transform_data manual__2025-03-12T14:37:42.059637+00:00 [queued]>
[2025-03-12T14:48:45.999+0000] {taskinstance.py:2867} INFO - Starting attempt 3 of 4
[2025-03-12T14:48:46.016+0000] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): transform_data> on 2025-03-12 14:37:42.059637+00:00
[2025-03-12T14:48:46.028+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=320) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-03-12T14:48:46.030+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'tiki_transform_dag', 'transform_data', 'manual__2025-03-12T14:37:42.059637+00:00', '--job-id', '770', '--raw', '--subdir', 'DAGS_FOLDER/tiki_transform_dag.py', '--cfg-path', '/tmp/tmpa3m43rcw']
[2025-03-12T14:48:46.031+0000] {standard_task_runner.py:72} INFO - Started process 329 to run task
[2025-03-12T14:48:46.032+0000] {standard_task_runner.py:105} INFO - Job 770: Subtask transform_data
[2025-03-12T14:48:46.091+0000] {task_command.py:467} INFO - Running <TaskInstance: tiki_transform_dag.transform_data manual__2025-03-12T14:37:42.059637+00:00 [running]> on host 3905098656d4
[2025-03-12T14:48:46.205+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='tiki_transform_dag' AIRFLOW_CTX_TASK_ID='transform_data' AIRFLOW_CTX_EXECUTION_DATE='2025-03-12T14:37:42.059637+00:00' AIRFLOW_CTX_TRY_NUMBER='3' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-03-12T14:37:42.059637+00:00'
[2025-03-12T14:48:46.207+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-03-12T14:48:46.207+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-03-12T14:48:46.208+0000] {logging_mixin.py:190} INFO - Current task name:transform_data state:running start_date:2025-03-12 14:48:45.990531+00:00
[2025-03-12T14:48:46.208+0000] {logging_mixin.py:190} INFO - Dag name:tiki_transform_dag and current dag run status:running
[2025-03-12T14:48:46.209+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-03-12T14:48:50.844+0000] {tiki_transform_dag.py:58} INFO - Loaded raw data from tiki-pipeline/tiki_raw_data/raw_dien-gia-dung_20250312_080050.json, 2000 rows
[2025-03-12T14:48:51.997+0000] {tiki_transform_dag.py:58} INFO - Loaded raw data from tiki-pipeline/tiki_raw_data/raw_dien-thoai-may-tinh-bang_20250312_074251.json, 361 rows
[2025-03-12T14:48:53.602+0000] {tiki_transform_dag.py:58} INFO - Loaded raw data from tiki-pipeline/tiki_raw_data/raw_dien-tu-dien-lanh_20250312_080131.json, 2000 rows
[2025-03-12T14:48:55.192+0000] {tiki_transform_dag.py:58} INFO - Loaded raw data from tiki-pipeline/tiki_raw_data/raw_dong-ho-va-trang-suc_20250312_074821.json, 2000 rows
[2025-03-12T14:48:56.901+0000] {tiki_transform_dag.py:58} INFO - Loaded raw data from tiki-pipeline/tiki_raw_data/raw_lam-dep-suc-khoe_20250312_074839.json, 2000 rows
[2025-03-12T14:48:58.476+0000] {tiki_transform_dag.py:58} INFO - Loaded raw data from tiki-pipeline/tiki_raw_data/raw_laptop-may-vi-tinh-linh-kien_20250312_080208.json, 2000 rows
[2025-03-12T14:49:00.134+0000] {tiki_transform_dag.py:58} INFO - Loaded raw data from tiki-pipeline/tiki_raw_data/raw_sach_20250312_074828.json, 2000 rows
[2025-03-12T14:49:01.761+0000] {tiki_transform_dag.py:58} INFO - Loaded raw data from tiki-pipeline/tiki_raw_data/raw_the-thao-da-ngoai_20250312_074838.json, 2000 rows
[2025-03-12T14:49:03.741+0000] {tiki_transform_dag.py:58} INFO - Loaded raw data from tiki-pipeline/tiki_raw_data/raw_thiet-bi-kts-phu-kien-so_20250312_080232.json, 2000 rows
[2025-03-12T14:49:05.835+0000] {tiki_transform_dag.py:58} INFO - Loaded raw data from tiki-pipeline/tiki_raw_data/raw_thoi-trang-nam_20250312_080215.json, 2000 rows
[2025-03-12T14:49:07.372+0000] {tiki_transform_dag.py:58} INFO - Loaded raw data from tiki-pipeline/tiki_raw_data/raw_thoi-trang-nu_20250312_080217.json, 2000 rows
[2025-03-12T14:49:07.404+0000] {tiki_transform_dag.py:68} INFO - After deduplication across all categories: 20357 rows
[2025-03-12T14:49:07.410+0000] {taskinstance.py:3313} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/tiki_transform_dag.py", line 79, in transform_data
    fact_df = df[[col for col in fact_cols if col in df.columns]].rename(columns={'id': 'product_id'}).drop_duplicates()
                                                     ^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'columns'
[2025-03-12T14:49:07.428+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2025-03-12T14:49:07.429+0000] {logging_mixin.py:190} INFO - Task start:2025-03-12 14:48:45.990531+00:00 end:2025-03-12 14:49:07.428154+00:00 duration:21.437623
[2025-03-12T14:49:07.429+0000] {logging_mixin.py:190} INFO - Task:<Task(PythonOperator): transform_data> dag:<DAG: tiki_transform_dag> dagrun:<DagRun tiki_transform_dag @ 2025-03-12 14:37:42.059637+00:00: manual__2025-03-12T14:37:42.059637+00:00, state:running, queued_at: 2025-03-12 14:37:42.078088+00:00. externally triggered: True>
[2025-03-12T14:49:07.430+0000] {logging_mixin.py:190} INFO - Failure caused by 'NoneType' object has no attribute 'columns'
[2025-03-12T14:49:07.430+0000] {taskinstance.py:1226} INFO - Marking task as UP_FOR_RETRY. dag_id=tiki_transform_dag, task_id=transform_data, run_id=manual__2025-03-12T14:37:42.059637+00:00, execution_date=20250312T143742, start_date=20250312T144845, end_date=20250312T144907
[2025-03-12T14:49:07.467+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-03-12T14:49:07.468+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 770 for task transform_data ('NoneType' object has no attribute 'columns'; 329)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3006, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 274, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3161, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3185, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/tiki_transform_dag.py", line 79, in transform_data
    fact_df = df[[col for col in fact_cols if col in df.columns]].rename(columns={'id': 'product_id'}).drop_duplicates()
                                                     ^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'columns'
[2025-03-12T14:49:07.532+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-03-12T14:49:07.557+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-12T14:49:07.560+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
