[2025-03-10T09:17:11.311+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-10T09:17:11.332+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: tiki_orchestration_dag.trigger_extract manual__2025-03-10T09:17:07.941496+00:00 [queued]>
[2025-03-10T09:17:11.343+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: tiki_orchestration_dag.trigger_extract manual__2025-03-10T09:17:07.941496+00:00 [queued]>
[2025-03-10T09:17:11.343+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 2
[2025-03-10T09:17:11.500+0000] {taskinstance.py:2890} INFO - Executing <Task(TriggerDagRunOperator): trigger_extract> on 2025-03-10 09:17:07.941496+00:00
[2025-03-10T09:17:11.509+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=1663) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-03-10T09:17:11.511+0000] {standard_task_runner.py:72} INFO - Started process 1665 to run task
[2025-03-10T09:17:11.511+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'tiki_orchestration_dag', 'trigger_extract', 'manual__2025-03-10T09:17:07.941496+00:00', '--job-id', '377', '--raw', '--subdir', 'DAGS_FOLDER/tiki_etl_orchestration.py', '--cfg-path', '/tmp/tmpxvcb78n1']
[2025-03-10T09:17:11.512+0000] {standard_task_runner.py:105} INFO - Job 377: Subtask trigger_extract
[2025-03-10T09:17:11.558+0000] {task_command.py:467} INFO - Running <TaskInstance: tiki_orchestration_dag.trigger_extract manual__2025-03-10T09:17:07.941496+00:00 [running]> on host c77555d100c4
[2025-03-10T09:17:11.636+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='tiki_orchestration_dag' AIRFLOW_CTX_TASK_ID='trigger_extract' AIRFLOW_CTX_EXECUTION_DATE='2025-03-10T09:17:07.941496+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-03-10T09:17:07.941496+00:00'
[2025-03-10T09:17:11.637+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-03-10T09:17:11.638+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-03-10T09:17:11.638+0000] {logging_mixin.py:190} INFO - Current task name:trigger_extract state:running start_date:2025-03-10 09:17:11.333477+00:00
[2025-03-10T09:17:11.639+0000] {logging_mixin.py:190} INFO - Dag name:tiki_orchestration_dag and current dag run status:running
[2025-03-10T09:17:11.639+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-03-10T09:17:11.708+0000] {trigger_dagrun.py:257} INFO - Waiting for tiki_extract_dag on 2025-03-10 09:17:11.640176+00:00 to become allowed state ['success'] ...
[2025-03-10T09:18:11.722+0000] {trigger_dagrun.py:257} INFO - Waiting for tiki_extract_dag on 2025-03-10 09:17:11.640176+00:00 to become allowed state ['success'] ...
[2025-03-10T09:19:11.728+0000] {trigger_dagrun.py:257} INFO - Waiting for tiki_extract_dag on 2025-03-10 09:17:11.640176+00:00 to become allowed state ['success'] ...
[2025-03-10T09:20:11.734+0000] {trigger_dagrun.py:257} INFO - Waiting for tiki_extract_dag on 2025-03-10 09:17:11.640176+00:00 to become allowed state ['success'] ...
[2025-03-10T09:21:11.740+0000] {trigger_dagrun.py:257} INFO - Waiting for tiki_extract_dag on 2025-03-10 09:17:11.640176+00:00 to become allowed state ['success'] ...
[2025-03-10T09:22:11.745+0000] {trigger_dagrun.py:257} INFO - Waiting for tiki_extract_dag on 2025-03-10 09:17:11.640176+00:00 to become allowed state ['success'] ...
[2025-03-10T09:23:11.752+0000] {trigger_dagrun.py:257} INFO - Waiting for tiki_extract_dag on 2025-03-10 09:17:11.640176+00:00 to become allowed state ['success'] ...
[2025-03-10T09:24:11.758+0000] {trigger_dagrun.py:257} INFO - Waiting for tiki_extract_dag on 2025-03-10 09:17:11.640176+00:00 to become allowed state ['success'] ...
[2025-03-10T09:25:11.764+0000] {trigger_dagrun.py:257} INFO - Waiting for tiki_extract_dag on 2025-03-10 09:17:11.640176+00:00 to become allowed state ['success'] ...
[2025-03-10T09:26:11.772+0000] {trigger_dagrun.py:257} INFO - Waiting for tiki_extract_dag on 2025-03-10 09:17:11.640176+00:00 to become allowed state ['success'] ...
[2025-03-10T09:27:11.781+0000] {trigger_dagrun.py:257} INFO - Waiting for tiki_extract_dag on 2025-03-10 09:17:11.640176+00:00 to become allowed state ['success'] ...
[2025-03-10T09:28:11.805+0000] {trigger_dagrun.py:257} INFO - Waiting for tiki_extract_dag on 2025-03-10 09:17:11.640176+00:00 to become allowed state ['success'] ...
[2025-03-10T09:29:11.819+0000] {trigger_dagrun.py:257} INFO - Waiting for tiki_extract_dag on 2025-03-10 09:17:11.640176+00:00 to become allowed state ['success'] ...
[2025-03-10T09:30:11.826+0000] {trigger_dagrun.py:257} INFO - Waiting for tiki_extract_dag on 2025-03-10 09:17:11.640176+00:00 to become allowed state ['success'] ...
[2025-03-10T09:31:11.833+0000] {trigger_dagrun.py:257} INFO - Waiting for tiki_extract_dag on 2025-03-10 09:17:11.640176+00:00 to become allowed state ['success'] ...
[2025-03-10T09:32:11.840+0000] {trigger_dagrun.py:257} INFO - Waiting for tiki_extract_dag on 2025-03-10 09:17:11.640176+00:00 to become allowed state ['success'] ...
[2025-03-10T09:33:11.846+0000] {trigger_dagrun.py:257} INFO - Waiting for tiki_extract_dag on 2025-03-10 09:17:11.640176+00:00 to become allowed state ['success'] ...
[2025-03-10T09:34:11.853+0000] {trigger_dagrun.py:257} INFO - Waiting for tiki_extract_dag on 2025-03-10 09:17:11.640176+00:00 to become allowed state ['success'] ...
[2025-03-10T09:35:11.858+0000] {trigger_dagrun.py:257} INFO - Waiting for tiki_extract_dag on 2025-03-10 09:17:11.640176+00:00 to become allowed state ['success'] ...
[2025-03-10T09:36:11.867+0000] {trigger_dagrun.py:257} INFO - Waiting for tiki_extract_dag on 2025-03-10 09:17:11.640176+00:00 to become allowed state ['success'] ...
[2025-03-10T09:37:11.873+0000] {trigger_dagrun.py:257} INFO - Waiting for tiki_extract_dag on 2025-03-10 09:17:11.640176+00:00 to become allowed state ['success'] ...
[2025-03-10T09:38:11.887+0000] {trigger_dagrun.py:257} INFO - Waiting for tiki_extract_dag on 2025-03-10 09:17:11.640176+00:00 to become allowed state ['success'] ...
[2025-03-10T09:39:11.897+0000] {trigger_dagrun.py:257} INFO - Waiting for tiki_extract_dag on 2025-03-10 09:17:11.640176+00:00 to become allowed state ['success'] ...
[2025-03-10T09:40:11.906+0000] {trigger_dagrun.py:257} INFO - Waiting for tiki_extract_dag on 2025-03-10 09:17:11.640176+00:00 to become allowed state ['success'] ...
[2025-03-10T09:41:11.914+0000] {trigger_dagrun.py:257} INFO - Waiting for tiki_extract_dag on 2025-03-10 09:17:11.640176+00:00 to become allowed state ['success'] ...
[2025-03-10T09:42:11.923+0000] {trigger_dagrun.py:257} INFO - Waiting for tiki_extract_dag on 2025-03-10 09:17:11.640176+00:00 to become allowed state ['success'] ...
[2025-03-10T09:43:11.930+0000] {trigger_dagrun.py:257} INFO - Waiting for tiki_extract_dag on 2025-03-10 09:17:11.640176+00:00 to become allowed state ['success'] ...
[2025-03-10T09:44:11.938+0000] {trigger_dagrun.py:257} INFO - Waiting for tiki_extract_dag on 2025-03-10 09:17:11.640176+00:00 to become allowed state ['success'] ...
[2025-03-10T09:45:11.945+0000] {trigger_dagrun.py:257} INFO - Waiting for tiki_extract_dag on 2025-03-10 09:17:11.640176+00:00 to become allowed state ['success'] ...
[2025-03-10T09:46:11.954+0000] {trigger_dagrun.py:257} INFO - Waiting for tiki_extract_dag on 2025-03-10 09:17:11.640176+00:00 to become allowed state ['success'] ...
[2025-03-10T09:47:11.962+0000] {trigger_dagrun.py:257} INFO - Waiting for tiki_extract_dag on 2025-03-10 09:17:11.640176+00:00 to become allowed state ['success'] ...
[2025-03-10T09:48:11.974+0000] {trigger_dagrun.py:257} INFO - Waiting for tiki_extract_dag on 2025-03-10 09:17:11.640176+00:00 to become allowed state ['success'] ...
[2025-03-10T09:49:11.981+0000] {trigger_dagrun.py:257} INFO - Waiting for tiki_extract_dag on 2025-03-10 09:17:11.640176+00:00 to become allowed state ['success'] ...
[2025-03-10T09:50:11.988+0000] {trigger_dagrun.py:257} INFO - Waiting for tiki_extract_dag on 2025-03-10 09:17:11.640176+00:00 to become allowed state ['success'] ...
[2025-03-10T09:51:11.995+0000] {trigger_dagrun.py:257} INFO - Waiting for tiki_extract_dag on 2025-03-10 09:17:11.640176+00:00 to become allowed state ['success'] ...
[2025-03-10T09:52:12.004+0000] {trigger_dagrun.py:257} INFO - Waiting for tiki_extract_dag on 2025-03-10 09:17:11.640176+00:00 to become allowed state ['success'] ...
[2025-03-10T09:53:12.011+0000] {trigger_dagrun.py:257} INFO - Waiting for tiki_extract_dag on 2025-03-10 09:17:11.640176+00:00 to become allowed state ['success'] ...
[2025-03-10T09:54:12.018+0000] {trigger_dagrun.py:257} INFO - Waiting for tiki_extract_dag on 2025-03-10 09:17:11.640176+00:00 to become allowed state ['success'] ...
[2025-03-10T09:55:12.026+0000] {trigger_dagrun.py:257} INFO - Waiting for tiki_extract_dag on 2025-03-10 09:17:11.640176+00:00 to become allowed state ['success'] ...
[2025-03-10T09:56:12.033+0000] {trigger_dagrun.py:257} INFO - Waiting for tiki_extract_dag on 2025-03-10 09:17:11.640176+00:00 to become allowed state ['success'] ...
[2025-03-10T09:57:12.043+0000] {trigger_dagrun.py:257} INFO - Waiting for tiki_extract_dag on 2025-03-10 09:17:11.640176+00:00 to become allowed state ['success'] ...
[2025-03-10T09:58:12.049+0000] {trigger_dagrun.py:257} INFO - Waiting for tiki_extract_dag on 2025-03-10 09:17:11.640176+00:00 to become allowed state ['success'] ...
[2025-03-10T09:59:12.056+0000] {trigger_dagrun.py:257} INFO - Waiting for tiki_extract_dag on 2025-03-10 09:17:11.640176+00:00 to become allowed state ['success'] ...
[2025-03-10T10:00:12.062+0000] {trigger_dagrun.py:257} INFO - Waiting for tiki_extract_dag on 2025-03-10 09:17:11.640176+00:00 to become allowed state ['success'] ...
[2025-03-10T10:01:12.070+0000] {trigger_dagrun.py:257} INFO - Waiting for tiki_extract_dag on 2025-03-10 09:17:11.640176+00:00 to become allowed state ['success'] ...
[2025-03-10T10:02:12.078+0000] {trigger_dagrun.py:257} INFO - Waiting for tiki_extract_dag on 2025-03-10 09:17:11.640176+00:00 to become allowed state ['success'] ...
[2025-03-10T10:03:12.086+0000] {trigger_dagrun.py:257} INFO - Waiting for tiki_extract_dag on 2025-03-10 09:17:11.640176+00:00 to become allowed state ['success'] ...
[2025-03-10T10:04:12.097+0000] {trigger_dagrun.py:257} INFO - Waiting for tiki_extract_dag on 2025-03-10 09:17:11.640176+00:00 to become allowed state ['success'] ...
[2025-03-10T10:05:12.103+0000] {trigger_dagrun.py:257} INFO - Waiting for tiki_extract_dag on 2025-03-10 09:17:11.640176+00:00 to become allowed state ['success'] ...
[2025-03-10T10:06:12.111+0000] {trigger_dagrun.py:257} INFO - Waiting for tiki_extract_dag on 2025-03-10 09:17:11.640176+00:00 to become allowed state ['success'] ...
[2025-03-10T10:07:12.117+0000] {trigger_dagrun.py:257} INFO - Waiting for tiki_extract_dag on 2025-03-10 09:17:11.640176+00:00 to become allowed state ['success'] ...
[2025-03-10T10:08:12.125+0000] {trigger_dagrun.py:257} INFO - Waiting for tiki_extract_dag on 2025-03-10 09:17:11.640176+00:00 to become allowed state ['success'] ...
[2025-03-10T10:09:12.132+0000] {trigger_dagrun.py:257} INFO - Waiting for tiki_extract_dag on 2025-03-10 09:17:11.640176+00:00 to become allowed state ['success'] ...
[2025-03-10T10:10:12.406+0000] {trigger_dagrun.py:257} INFO - Waiting for tiki_extract_dag on 2025-03-10 09:17:11.640176+00:00 to become allowed state ['success'] ...
[2025-03-10T10:10:43.058+0000] {job.py:229} INFO - Heartbeat recovered after 31.41 seconds
[2025-03-10T10:11:17.086+0000] {trigger_dagrun.py:257} INFO - Waiting for tiki_extract_dag on 2025-03-10 09:17:11.640176+00:00 to become allowed state ['success'] ...
[2025-03-10T10:11:17.068+0000] {job.py:229} INFO - Heartbeat recovered after 20.72 seconds
[2025-03-10T10:12:17.155+0000] {trigger_dagrun.py:257} INFO - Waiting for tiki_extract_dag on 2025-03-10 09:17:11.640176+00:00 to become allowed state ['success'] ...
[2025-03-10T10:13:17.163+0000] {trigger_dagrun.py:257} INFO - Waiting for tiki_extract_dag on 2025-03-10 09:17:11.640176+00:00 to become allowed state ['success'] ...
[2025-03-10T10:14:17.172+0000] {trigger_dagrun.py:257} INFO - Waiting for tiki_extract_dag on 2025-03-10 09:17:11.640176+00:00 to become allowed state ['success'] ...
[2025-03-10T10:15:17.184+0000] {trigger_dagrun.py:257} INFO - Waiting for tiki_extract_dag on 2025-03-10 09:17:11.640176+00:00 to become allowed state ['success'] ...
[2025-03-10T10:16:17.196+0000] {trigger_dagrun.py:257} INFO - Waiting for tiki_extract_dag on 2025-03-10 09:17:11.640176+00:00 to become allowed state ['success'] ...
[2025-03-10T10:17:39.762+0000] {taskinstance.py:3313} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 3371, in _wrap_pool_connect
    return fn()
           ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 327, in connect
    return _ConnectionFairy._checkout(self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 894, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 493, in checkout
    rec = pool._do_get()
          ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/impl.py", line 256, in _do_get
    return self._create_connection()
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 273, in _create_connection
    return _ConnectionRecord(self)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 388, in __init__
    self.__connect()
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 690, in __connect
    with util.safe_reraise():
         ^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 686, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/create.py", line 574, in connect
    return dialect.connect(*cargs, **cparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/default.py", line 598, in connect
    return self.dbapi.connect(*cargs, **cparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
psycopg2.OperationalError: could not translate host name "postgres" to address: Temporary failure in name resolution


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/trigger_dagrun.py", line 266, in execute
    dag_run.refresh_from_db()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagrun.py", line 359, in refresh_from_db
    dr = session.scalars(
         ^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 1778, in scalars
    return self.execute(
           ^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 1716, in execute
    conn = self._connection_for_bind(bind)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 1555, in _connection_for_bind
    return self._transaction._connection_for_bind(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 750, in _connection_for_bind
    conn = bind.connect()
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/future/engine.py", line 412, in connect
    return super(Engine, self).connect()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 3325, in connect
    return self._connection_cls(self, close_with_result=close_with_result)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 96, in __init__
    else engine.raw_connection()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 3404, in raw_connection
    return self._wrap_pool_connect(self.pool.connect, _connection)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 3374, in _wrap_pool_connect
    Connection._handle_dbapi_exception_noconnection(
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 2208, in _handle_dbapi_exception_noconnection
    util.raise_(
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 3371, in _wrap_pool_connect
    return fn()
           ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 327, in connect
    return _ConnectionFairy._checkout(self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 894, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 493, in checkout
    rec = pool._do_get()
          ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/impl.py", line 256, in _do_get
    return self._create_connection()
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 273, in _create_connection
    return _ConnectionRecord(self)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 388, in __init__
    self.__connect()
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 690, in __connect
    with util.safe_reraise():
         ^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 686, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/create.py", line 574, in connect
    return dialect.connect(*cargs, **cparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/default.py", line 598, in connect
    return self.dbapi.connect(*cargs, **cparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) could not translate host name "postgres" to address: Temporary failure in name resolution

(Background on this error at: https://sqlalche.me/e/14/e3q8)
[2025-03-10T10:17:40.430+0000] {job.py:229} INFO - Heartbeat recovered after 39.02 seconds
[2025-03-10T10:17:41.018+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2025-03-10T10:17:41.032+0000] {logging_mixin.py:190} INFO - Task start:2025-03-10 09:17:11.333477+00:00 end:2025-03-10 10:17:40.849485+00:00 duration:3629.516008
[2025-03-10T10:17:41.054+0000] {logging_mixin.py:190} INFO - Task:<Task(TriggerDagRunOperator): trigger_extract> dag:<DAG: tiki_orchestration_dag> dagrun:<DagRun tiki_orchestration_dag @ 2025-03-10 09:17:07.941496+00:00: manual__2025-03-10T09:17:07.941496+00:00, state:running, queued_at: 2025-03-10 09:17:08.002465+00:00. externally triggered: True>
[2025-03-10T10:17:41.055+0000] {logging_mixin.py:190} INFO - Failure caused by (psycopg2.OperationalError) could not translate host name "postgres" to address: Temporary failure in name resolution

(Background on this error at: https://sqlalche.me/e/14/e3q8)
[2025-03-10T10:17:41.090+0000] {taskinstance.py:1226} INFO - Marking task as UP_FOR_RETRY. dag_id=tiki_orchestration_dag, task_id=trigger_extract, run_id=manual__2025-03-10T09:17:07.941496+00:00, execution_date=20250310T091707, start_date=20250310T091711, end_date=20250310T101740
[2025-03-10T10:17:42.369+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-03-10T10:17:42.409+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 377 for task trigger_extract ((psycopg2.OperationalError) could not translate host name "postgres" to address: Temporary failure in name resolution

(Background on this error at: https://sqlalche.me/e/14/e3q8); 1665)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 3371, in _wrap_pool_connect
    return fn()
           ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 327, in connect
    return _ConnectionFairy._checkout(self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 894, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 493, in checkout
    rec = pool._do_get()
          ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/impl.py", line 256, in _do_get
    return self._create_connection()
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 273, in _create_connection
    return _ConnectionRecord(self)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 388, in __init__
    self.__connect()
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 690, in __connect
    with util.safe_reraise():
         ^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 686, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/create.py", line 574, in connect
    return dialect.connect(*cargs, **cparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/default.py", line 598, in connect
    return self.dbapi.connect(*cargs, **cparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
psycopg2.OperationalError: could not translate host name "postgres" to address: Temporary failure in name resolution


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3006, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 274, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3161, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3185, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/trigger_dagrun.py", line 266, in execute
    dag_run.refresh_from_db()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagrun.py", line 359, in refresh_from_db
    dr = session.scalars(
         ^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 1778, in scalars
    return self.execute(
           ^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 1716, in execute
    conn = self._connection_for_bind(bind)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 1555, in _connection_for_bind
    return self._transaction._connection_for_bind(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 750, in _connection_for_bind
    conn = bind.connect()
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/future/engine.py", line 412, in connect
    return super(Engine, self).connect()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 3325, in connect
    return self._connection_cls(self, close_with_result=close_with_result)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 96, in __init__
    else engine.raw_connection()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 3404, in raw_connection
    return self._wrap_pool_connect(self.pool.connect, _connection)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 3374, in _wrap_pool_connect
    Connection._handle_dbapi_exception_noconnection(
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 2208, in _handle_dbapi_exception_noconnection
    util.raise_(
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 3371, in _wrap_pool_connect
    return fn()
           ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 327, in connect
    return _ConnectionFairy._checkout(self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 894, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 493, in checkout
    rec = pool._do_get()
          ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/impl.py", line 256, in _do_get
    return self._create_connection()
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 273, in _create_connection
    return _ConnectionRecord(self)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 388, in __init__
    self.__connect()
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 690, in __connect
    with util.safe_reraise():
         ^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 686, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/create.py", line 574, in connect
    return dialect.connect(*cargs, **cparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/default.py", line 598, in connect
    return self.dbapi.connect(*cargs, **cparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) could not translate host name "postgres" to address: Temporary failure in name resolution

(Background on this error at: https://sqlalche.me/e/14/e3q8)
[2025-03-10T10:17:42.997+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-03-10T10:17:44.691+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-10T10:17:44.891+0000] {standard_task_runner.py:217} INFO - Process not found (most likely exited), stop collecting metrics
[2025-03-10T10:17:44.979+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
