[2025-03-10T08:03:57.034+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-10T08:03:57.053+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: tiki_schema_management_dag.create_schema manual__2025-03-10T08:03:52.063974+00:00 [queued]>
[2025-03-10T08:03:57.066+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: tiki_schema_management_dag.create_schema manual__2025-03-10T08:03:52.063974+00:00 [queued]>
[2025-03-10T08:03:57.067+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 1
[2025-03-10T08:03:57.306+0000] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): create_schema> on 2025-03-10 08:03:52.063974+00:00
[2025-03-10T08:03:57.323+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=527) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-03-10T08:03:57.327+0000] {standard_task_runner.py:72} INFO - Started process 536 to run task
[2025-03-10T08:03:57.328+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'tiki_schema_management_dag', 'create_schema', 'manual__2025-03-10T08:03:52.063974+00:00', '--job-id', '323', '--raw', '--subdir', 'DAGS_FOLDER/tiki_schema_management_dag.py', '--cfg-path', '/tmp/tmpre0kayns']
[2025-03-10T08:03:57.330+0000] {standard_task_runner.py:105} INFO - Job 323: Subtask create_schema
[2025-03-10T08:03:57.429+0000] {task_command.py:467} INFO - Running <TaskInstance: tiki_schema_management_dag.create_schema manual__2025-03-10T08:03:52.063974+00:00 [running]> on host c77555d100c4
[2025-03-10T08:03:57.573+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='tiki_schema_management_dag' AIRFLOW_CTX_TASK_ID='create_schema' AIRFLOW_CTX_EXECUTION_DATE='2025-03-10T08:03:52.063974+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-03-10T08:03:52.063974+00:00'
[2025-03-10T08:03:57.575+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-03-10T08:03:57.576+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-03-10T08:03:57.577+0000] {logging_mixin.py:190} INFO - Current task name:create_schema state:running start_date:2025-03-10 08:03:57.054661+00:00
[2025-03-10T08:03:57.578+0000] {logging_mixin.py:190} INFO - Dag name:tiki_schema_management_dag and current dag run status:running
[2025-03-10T08:03:57.578+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-03-10T08:03:57.594+0000] {tiki_schema_management_dag.py:32} INFO - Using project_id: vietadc, dataset_id: tiki_data, table_names: {'fact_sales': 'Fact_Sales', 'dim_product': 'Dim_Product', 'dim_seller': 'Dim_Seller', 'dim_category': 'Dim_Category', 'dim_brand': 'Dim_Brand'}
[2025-03-10T08:03:59.696+0000] {tiki_schema_management_dag.py:42} INFO - Created/Updated dataset vietadc.tiki_data
[2025-03-10T08:03:59.697+0000] {tiki_schema_management_dag.py:107} ERROR - Error creating schema: 'dim_flags'
[2025-03-10T08:03:59.698+0000] {taskinstance.py:3313} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/tiki_schema_management_dag.py", line 84, in create_schema
    table_names['dim_flags']: [
    ~~~~~~~~~~~^^^^^^^^^^^^^
KeyError: 'dim_flags'
[2025-03-10T08:03:59.719+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2025-03-10T08:03:59.720+0000] {logging_mixin.py:190} INFO - Task start:2025-03-10 08:03:57.054661+00:00 end:2025-03-10 08:03:59.719048+00:00 duration:2.664387
[2025-03-10T08:03:59.721+0000] {logging_mixin.py:190} INFO - Task:<Task(PythonOperator): create_schema> dag:<DAG: tiki_schema_management_dag> dagrun:<DagRun tiki_schema_management_dag @ 2025-03-10 08:03:52.063974+00:00: manual__2025-03-10T08:03:52.063974+00:00, state:running, queued_at: 2025-03-10 08:03:52.108024+00:00. externally triggered: True>
[2025-03-10T08:03:59.721+0000] {logging_mixin.py:190} INFO - Failure caused by 'dim_flags'
[2025-03-10T08:03:59.722+0000] {taskinstance.py:1226} INFO - Marking task as FAILED. dag_id=tiki_schema_management_dag, task_id=create_schema, run_id=manual__2025-03-10T08:03:52.063974+00:00, execution_date=20250310T080352, start_date=20250310T080357, end_date=20250310T080359
[2025-03-10T08:03:59.757+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-03-10T08:03:59.758+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 323 for task create_schema ('dim_flags'; 536)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3006, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 274, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3161, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3185, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/tiki_schema_management_dag.py", line 84, in create_schema
    table_names['dim_flags']: [
    ~~~~~~~~~~~^^^^^^^^^^^^^
KeyError: 'dim_flags'
[2025-03-10T08:03:59.797+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-03-10T08:03:59.822+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-10T08:03:59.825+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
