[2025-03-10T09:07:50.798+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-10T09:07:50.828+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: tiki_orchestration_dag.trigger_transform manual__2025-03-10T09:06:44.009920+00:00 [queued]>
[2025-03-10T09:07:50.841+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: tiki_orchestration_dag.trigger_transform manual__2025-03-10T09:06:44.009920+00:00 [queued]>
[2025-03-10T09:07:50.842+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 2
[2025-03-10T09:07:50.860+0000] {taskinstance.py:2890} INFO - Executing <Task(TriggerDagRunOperator): trigger_transform> on 2025-03-10 09:06:44.009920+00:00
[2025-03-10T09:07:50.871+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=1502) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-03-10T09:07:50.872+0000] {standard_task_runner.py:72} INFO - Started process 1504 to run task
[2025-03-10T09:07:50.873+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'tiki_orchestration_dag', 'trigger_transform', 'manual__2025-03-10T09:06:44.009920+00:00', '--job-id', '365', '--raw', '--subdir', 'DAGS_FOLDER/tiki_etl_orchestration.py', '--cfg-path', '/tmp/tmpgvy6hcdz']
[2025-03-10T09:07:50.874+0000] {standard_task_runner.py:105} INFO - Job 365: Subtask trigger_transform
[2025-03-10T09:07:51.249+0000] {task_command.py:467} INFO - Running <TaskInstance: tiki_orchestration_dag.trigger_transform manual__2025-03-10T09:06:44.009920+00:00 [running]> on host c77555d100c4
[2025-03-10T09:07:51.337+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='tiki_orchestration_dag' AIRFLOW_CTX_TASK_ID='trigger_transform' AIRFLOW_CTX_EXECUTION_DATE='2025-03-10T09:06:44.009920+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-03-10T09:06:44.009920+00:00'
[2025-03-10T09:07:51.339+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-03-10T09:07:51.339+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-03-10T09:07:51.340+0000] {logging_mixin.py:190} INFO - Current task name:trigger_transform state:running start_date:2025-03-10 09:07:50.829609+00:00
[2025-03-10T09:07:51.340+0000] {logging_mixin.py:190} INFO - Dag name:tiki_orchestration_dag and current dag run status:running
[2025-03-10T09:07:51.341+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-03-10T09:07:51.422+0000] {trigger_dagrun.py:257} INFO - Waiting for tiki_transform_dag on 2025-03-10 09:07:51.341496+00:00 to become allowed state ['success'] ...
[2025-03-10T09:08:51.430+0000] {trigger_dagrun.py:257} INFO - Waiting for tiki_transform_dag on 2025-03-10 09:07:51.341496+00:00 to become allowed state ['success'] ...
[2025-03-10T09:09:51.436+0000] {trigger_dagrun.py:257} INFO - Waiting for tiki_transform_dag on 2025-03-10 09:07:51.341496+00:00 to become allowed state ['success'] ...
[2025-03-10T09:10:51.444+0000] {trigger_dagrun.py:257} INFO - Waiting for tiki_transform_dag on 2025-03-10 09:07:51.341496+00:00 to become allowed state ['success'] ...
[2025-03-10T09:11:51.452+0000] {trigger_dagrun.py:257} INFO - Waiting for tiki_transform_dag on 2025-03-10 09:07:51.341496+00:00 to become allowed state ['success'] ...
[2025-03-10T09:12:51.459+0000] {trigger_dagrun.py:257} INFO - Waiting for tiki_transform_dag on 2025-03-10 09:07:51.341496+00:00 to become allowed state ['success'] ...
[2025-03-10T09:13:51.472+0000] {trigger_dagrun.py:257} INFO - Waiting for tiki_transform_dag on 2025-03-10 09:07:51.341496+00:00 to become allowed state ['success'] ...
[2025-03-10T09:14:51.482+0000] {trigger_dagrun.py:257} INFO - Waiting for tiki_transform_dag on 2025-03-10 09:07:51.341496+00:00 to become allowed state ['success'] ...
[2025-03-10T09:15:51.491+0000] {trigger_dagrun.py:257} INFO - Waiting for tiki_transform_dag on 2025-03-10 09:07:51.341496+00:00 to become allowed state ['success'] ...
[2025-03-10T09:16:51.503+0000] {trigger_dagrun.py:257} INFO - Waiting for tiki_transform_dag on 2025-03-10 09:07:51.341496+00:00 to become allowed state ['success'] ...
[2025-03-10T09:17:51.520+0000] {trigger_dagrun.py:257} INFO - Waiting for tiki_transform_dag on 2025-03-10 09:07:51.341496+00:00 to become allowed state ['success'] ...
[2025-03-10T09:18:51.535+0000] {trigger_dagrun.py:257} INFO - Waiting for tiki_transform_dag on 2025-03-10 09:07:51.341496+00:00 to become allowed state ['success'] ...
[2025-03-10T09:19:51.558+0000] {trigger_dagrun.py:257} INFO - Waiting for tiki_transform_dag on 2025-03-10 09:07:51.341496+00:00 to become allowed state ['success'] ...
[2025-03-10T09:20:51.572+0000] {trigger_dagrun.py:257} INFO - Waiting for tiki_transform_dag on 2025-03-10 09:07:51.341496+00:00 to become allowed state ['success'] ...
[2025-03-10T09:21:51.580+0000] {trigger_dagrun.py:257} INFO - Waiting for tiki_transform_dag on 2025-03-10 09:07:51.341496+00:00 to become allowed state ['success'] ...
[2025-03-10T09:22:51.590+0000] {trigger_dagrun.py:257} INFO - Waiting for tiki_transform_dag on 2025-03-10 09:07:51.341496+00:00 to become allowed state ['success'] ...
[2025-03-10T09:23:51.697+0000] {taskinstance.py:3313} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/trigger_dagrun.py", line 269, in execute
    raise AirflowException(f"{self.trigger_dag_id} failed with failed states {state}")
airflow.exceptions.AirflowException: tiki_transform_dag failed with failed states failed
[2025-03-10T09:23:51.766+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2025-03-10T09:23:51.768+0000] {logging_mixin.py:190} INFO - Task start:2025-03-10 09:07:50.829609+00:00 end:2025-03-10 09:23:51.757384+00:00 duration:960.927775
[2025-03-10T09:23:51.771+0000] {logging_mixin.py:190} INFO - Task:<Task(TriggerDagRunOperator): trigger_transform> dag:<DAG: tiki_orchestration_dag> dagrun:<DagRun tiki_orchestration_dag @ 2025-03-10 09:06:44.009920+00:00: manual__2025-03-10T09:06:44.009920+00:00, state:running, queued_at: 2025-03-10 09:06:44.030096+00:00. externally triggered: True>
[2025-03-10T09:23:51.772+0000] {logging_mixin.py:190} INFO - Failure caused by tiki_transform_dag failed with failed states failed
[2025-03-10T09:23:51.772+0000] {taskinstance.py:1226} INFO - Marking task as UP_FOR_RETRY. dag_id=tiki_orchestration_dag, task_id=trigger_transform, run_id=manual__2025-03-10T09:06:44.009920+00:00, execution_date=20250310T090644, start_date=20250310T090750, end_date=20250310T092351
[2025-03-10T09:23:51.860+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-03-10T09:23:51.864+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 365 for task trigger_transform (tiki_transform_dag failed with failed states failed; 1504)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3006, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 274, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3161, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3185, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/trigger_dagrun.py", line 269, in execute
    raise AirflowException(f"{self.trigger_dag_id} failed with failed states {state}")
airflow.exceptions.AirflowException: tiki_transform_dag failed with failed states failed
[2025-03-10T09:23:51.950+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-03-10T09:23:52.007+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
