[2025-03-10T09:31:31.797+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-10T09:31:31.824+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: tiki_orchestration_dag.trigger_transform manual__2025-03-10T09:09:20.206614+00:00 [queued]>
[2025-03-10T09:31:31.836+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: tiki_orchestration_dag.trigger_transform manual__2025-03-10T09:09:20.206614+00:00 [queued]>
[2025-03-10T09:31:31.837+0000] {taskinstance.py:2867} INFO - Starting attempt 2 of 2
[2025-03-10T09:31:31.855+0000] {taskinstance.py:2890} INFO - Executing <Task(TriggerDagRunOperator): trigger_transform> on 2025-03-10 09:09:20.206614+00:00
[2025-03-10T09:31:31.865+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=1890) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-03-10T09:31:31.867+0000] {standard_task_runner.py:72} INFO - Started process 1892 to run task
[2025-03-10T09:31:31.867+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'tiki_orchestration_dag', 'trigger_transform', 'manual__2025-03-10T09:09:20.206614+00:00', '--job-id', '388', '--raw', '--subdir', 'DAGS_FOLDER/tiki_etl_orchestration.py', '--cfg-path', '/tmp/tmp65go9mnj']
[2025-03-10T09:31:31.868+0000] {standard_task_runner.py:105} INFO - Job 388: Subtask trigger_transform
[2025-03-10T09:31:32.215+0000] {task_command.py:467} INFO - Running <TaskInstance: tiki_orchestration_dag.trigger_transform manual__2025-03-10T09:09:20.206614+00:00 [running]> on host c77555d100c4
[2025-03-10T09:31:32.310+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='tiki_orchestration_dag' AIRFLOW_CTX_TASK_ID='trigger_transform' AIRFLOW_CTX_EXECUTION_DATE='2025-03-10T09:09:20.206614+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-03-10T09:09:20.206614+00:00'
[2025-03-10T09:31:32.311+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-03-10T09:31:32.312+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-03-10T09:31:32.312+0000] {logging_mixin.py:190} INFO - Current task name:trigger_transform state:running start_date:2025-03-10 09:31:31.825675+00:00
[2025-03-10T09:31:32.313+0000] {logging_mixin.py:190} INFO - Dag name:tiki_orchestration_dag and current dag run status:running
[2025-03-10T09:31:32.313+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-03-10T09:31:32.390+0000] {trigger_dagrun.py:257} INFO - Waiting for tiki_transform_dag on 2025-03-10 09:31:32.314164+00:00 to become allowed state ['success'] ...
[2025-03-10T09:32:32.423+0000] {trigger_dagrun.py:257} INFO - Waiting for tiki_transform_dag on 2025-03-10 09:31:32.314164+00:00 to become allowed state ['success'] ...
[2025-03-10T09:33:32.438+0000] {trigger_dagrun.py:257} INFO - Waiting for tiki_transform_dag on 2025-03-10 09:31:32.314164+00:00 to become allowed state ['success'] ...
[2025-03-10T09:34:32.446+0000] {trigger_dagrun.py:257} INFO - Waiting for tiki_transform_dag on 2025-03-10 09:31:32.314164+00:00 to become allowed state ['success'] ...
[2025-03-10T09:35:32.452+0000] {trigger_dagrun.py:257} INFO - Waiting for tiki_transform_dag on 2025-03-10 09:31:32.314164+00:00 to become allowed state ['success'] ...
[2025-03-10T09:36:32.460+0000] {trigger_dagrun.py:257} INFO - Waiting for tiki_transform_dag on 2025-03-10 09:31:32.314164+00:00 to become allowed state ['success'] ...
[2025-03-10T09:37:32.469+0000] {trigger_dagrun.py:257} INFO - Waiting for tiki_transform_dag on 2025-03-10 09:31:32.314164+00:00 to become allowed state ['success'] ...
[2025-03-10T09:38:32.481+0000] {trigger_dagrun.py:257} INFO - Waiting for tiki_transform_dag on 2025-03-10 09:31:32.314164+00:00 to become allowed state ['success'] ...
[2025-03-10T09:39:32.488+0000] {trigger_dagrun.py:257} INFO - Waiting for tiki_transform_dag on 2025-03-10 09:31:32.314164+00:00 to become allowed state ['success'] ...
[2025-03-10T09:40:32.494+0000] {trigger_dagrun.py:257} INFO - Waiting for tiki_transform_dag on 2025-03-10 09:31:32.314164+00:00 to become allowed state ['success'] ...
[2025-03-10T09:41:32.502+0000] {trigger_dagrun.py:257} INFO - Waiting for tiki_transform_dag on 2025-03-10 09:31:32.314164+00:00 to become allowed state ['success'] ...
[2025-03-10T09:42:32.512+0000] {trigger_dagrun.py:257} INFO - Waiting for tiki_transform_dag on 2025-03-10 09:31:32.314164+00:00 to become allowed state ['success'] ...
[2025-03-10T09:43:32.520+0000] {trigger_dagrun.py:257} INFO - Waiting for tiki_transform_dag on 2025-03-10 09:31:32.314164+00:00 to become allowed state ['success'] ...
[2025-03-10T09:44:32.533+0000] {trigger_dagrun.py:257} INFO - Waiting for tiki_transform_dag on 2025-03-10 09:31:32.314164+00:00 to become allowed state ['success'] ...
[2025-03-10T09:45:32.541+0000] {trigger_dagrun.py:257} INFO - Waiting for tiki_transform_dag on 2025-03-10 09:31:32.314164+00:00 to become allowed state ['success'] ...
[2025-03-10T09:46:32.549+0000] {trigger_dagrun.py:257} INFO - Waiting for tiki_transform_dag on 2025-03-10 09:31:32.314164+00:00 to become allowed state ['success'] ...
[2025-03-10T09:47:32.586+0000] {taskinstance.py:3313} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/trigger_dagrun.py", line 269, in execute
    raise AirflowException(f"{self.trigger_dag_id} failed with failed states {state}")
airflow.exceptions.AirflowException: tiki_transform_dag failed with failed states failed
[2025-03-10T09:47:32.599+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2025-03-10T09:47:32.600+0000] {logging_mixin.py:190} INFO - Task start:2025-03-10 09:31:31.825675+00:00 end:2025-03-10 09:47:32.595010+00:00 duration:960.769335
[2025-03-10T09:47:32.601+0000] {logging_mixin.py:190} INFO - Task:<Task(TriggerDagRunOperator): trigger_transform> dag:<DAG: tiki_orchestration_dag> dagrun:<DagRun tiki_orchestration_dag @ 2025-03-10 09:09:20.206614+00:00: manual__2025-03-10T09:09:20.206614+00:00, state:running, queued_at: 2025-03-10 09:09:20.243134+00:00. externally triggered: True>
[2025-03-10T09:47:32.602+0000] {logging_mixin.py:190} INFO - Failure caused by tiki_transform_dag failed with failed states failed
[2025-03-10T09:47:32.602+0000] {taskinstance.py:1226} INFO - Marking task as FAILED. dag_id=tiki_orchestration_dag, task_id=trigger_transform, run_id=manual__2025-03-10T09:09:20.206614+00:00, execution_date=20250310T090920, start_date=20250310T093131, end_date=20250310T094732
[2025-03-10T09:47:32.649+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-03-10T09:47:32.651+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 388 for task trigger_transform (tiki_transform_dag failed with failed states failed; 1892)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3006, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 274, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3161, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3185, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/trigger_dagrun.py", line 269, in execute
    raise AirflowException(f"{self.trigger_dag_id} failed with failed states {state}")
airflow.exceptions.AirflowException: tiki_transform_dag failed with failed states failed
[2025-03-10T09:47:32.718+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-03-10T09:47:32.786+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-10T09:47:32.794+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
